# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(500, 700)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.tbl_file = QtWidgets.QTableWidget(self.centralwidget)
        self.tbl_file.setObjectName("tbl_file")
        self.tbl_file.setColumnCount(5)
        self.tbl_file.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_file.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_file.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_file.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_file.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_file.setHorizontalHeaderItem(4, item)
        self.gridLayout_4.addWidget(self.tbl_file, 2, 0, 1, 4)
        self.lbl_log = QtWidgets.QLabel(self.centralwidget)
        self.lbl_log.setObjectName("lbl_log")
        self.gridLayout_4.addWidget(self.lbl_log, 4, 0, 1, 1)
        self.txt_log = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.txt_log.setReadOnly(True)
        self.txt_log.setObjectName("txt_log")
        self.gridLayout_4.addWidget(self.txt_log, 5, 0, 1, 4)
        self.btn_add = QtWidgets.QPushButton(self.centralwidget)
        self.btn_add.setObjectName("btn_add")
        self.gridLayout_4.addWidget(self.btn_add, 3, 0, 1, 1)
        self.lbl_file_list = QtWidgets.QLabel(self.centralwidget)
        self.lbl_file_list.setObjectName("lbl_file_list")
        self.gridLayout_4.addWidget(self.lbl_file_list, 1, 0, 1, 1)
        self.btn_clear = QtWidgets.QPushButton(self.centralwidget)
        self.btn_clear.setObjectName("btn_clear")
        self.gridLayout_4.addWidget(self.btn_clear, 3, 1, 1, 1)
        self.widget_tr = QtWidgets.QWidget(self.centralwidget)
        self.widget_tr.setObjectName("widget_tr")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widget_tr)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.lbl_user = QtWidgets.QLabel(self.widget_tr)
        self.lbl_user.setObjectName("lbl_user")
        self.gridLayout_2.addWidget(self.lbl_user, 0, 0, 1, 1)
        self.fld_user = QtWidgets.QLineEdit(self.widget_tr)
        self.fld_user.setObjectName("fld_user")
        self.gridLayout_2.addWidget(self.fld_user, 0, 1, 1, 1)
        self.lbl_password = QtWidgets.QLabel(self.widget_tr)
        self.lbl_password.setObjectName("lbl_password")
        self.gridLayout_2.addWidget(self.lbl_password, 1, 0, 1, 1)
        self.fld_password = QtWidgets.QLineEdit(self.widget_tr)
        self.fld_password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.fld_password.setObjectName("fld_password")
        self.gridLayout_2.addWidget(self.fld_password, 1, 1, 1, 1)
        self.btn_test = QtWidgets.QPushButton(self.widget_tr)
        self.btn_test.setObjectName("btn_test")
        self.gridLayout_2.addWidget(self.btn_test, 2, 0, 1, 2)
        self.gridLayout_4.addWidget(self.widget_tr, 0, 2, 1, 2)
        self.widget_tl = QtWidgets.QWidget(self.centralwidget)
        self.widget_tl.setObjectName("widget_tl")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.widget_tl)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.lbl_host = QtWidgets.QLabel(self.widget_tl)
        self.lbl_host.setObjectName("lbl_host")
        self.gridLayout_3.addWidget(self.lbl_host, 0, 0, 1, 1)
        self.fld_host = QtWidgets.QLineEdit(self.widget_tl)
        self.fld_host.setObjectName("fld_host")
        self.gridLayout_3.addWidget(self.fld_host, 0, 1, 1, 1)
        self.lbl_port = QtWidgets.QLabel(self.widget_tl)
        self.lbl_port.setObjectName("lbl_port")
        self.gridLayout_3.addWidget(self.lbl_port, 1, 0, 1, 1)
        self.fld_port = QtWidgets.QLineEdit(self.widget_tl)
        self.fld_port.setObjectName("fld_port")
        self.gridLayout_3.addWidget(self.fld_port, 1, 1, 1, 1)
        self.lbl_dbname = QtWidgets.QLabel(self.widget_tl)
        self.lbl_dbname.setObjectName("lbl_dbname")
        self.gridLayout_3.addWidget(self.lbl_dbname, 2, 0, 1, 1)
        self.fld_dbname = QtWidgets.QLineEdit(self.widget_tl)
        self.fld_dbname.setObjectName("fld_dbname")
        self.gridLayout_3.addWidget(self.fld_dbname, 2, 1, 1, 1)
        self.gridLayout_4.addWidget(self.widget_tl, 0, 0, 1, 2)
        self.btn_import = QtWidgets.QPushButton(self.centralwidget)
        self.btn_import.setObjectName("btn_import")
        self.gridLayout_4.addWidget(self.btn_import, 6, 2, 1, 2)
        self.btn_save_log = QtWidgets.QPushButton(self.centralwidget)
        self.btn_save_log.setObjectName("btn_save_log")
        self.gridLayout_4.addWidget(self.btn_save_log, 6, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 500, 22))
        self.menubar.setObjectName("menubar")
        self.menu_File = QtWidgets.QMenu(self.menubar)
        self.menu_File.setObjectName("menu_File")
        self.menu_Help = QtWidgets.QMenu(self.menubar)
        self.menu_Help.setObjectName("menu_Help")
        MainWindow.setMenuBar(self.menubar)
        self.act_add = QtWidgets.QAction(MainWindow)
        self.act_add.setObjectName("act_add")
        self.act_about = QtWidgets.QAction(MainWindow)
        self.act_about.setObjectName("act_about")
        self.menu_File.addAction(self.act_add)
        self.menu_Help.addAction(self.act_about)
        self.menubar.addAction(self.menu_File.menuAction())
        self.menubar.addAction(self.menu_Help.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.fld_host, self.fld_port)
        MainWindow.setTabOrder(self.fld_port, self.fld_dbname)
        MainWindow.setTabOrder(self.fld_dbname, self.fld_user)
        MainWindow.setTabOrder(self.fld_user, self.fld_password)
        MainWindow.setTabOrder(self.fld_password, self.btn_test)
        MainWindow.setTabOrder(self.btn_test, self.tbl_file)
        MainWindow.setTabOrder(self.tbl_file, self.btn_add)
        MainWindow.setTabOrder(self.btn_add, self.btn_clear)
        MainWindow.setTabOrder(self.btn_clear, self.txt_log)
        MainWindow.setTabOrder(self.txt_log, self.btn_save_log)
        MainWindow.setTabOrder(self.btn_save_log, self.btn_import)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Shp2PgsqlGUI"))
        item = self.tbl_file.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Source"))
        item = self.tbl_file.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Schema"))
        item = self.tbl_file.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Table"))
        item = self.tbl_file.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Geom Column"))
        item = self.tbl_file.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "SRID"))
        self.lbl_log.setText(_translate("MainWindow", "Log"))
        self.btn_add.setText(_translate("MainWindow", "Add File"))
        self.lbl_file_list.setText(_translate("MainWindow", "File list"))
        self.btn_clear.setText(_translate("MainWindow", "Clear"))
        self.lbl_user.setText(_translate("MainWindow", "Username"))
        self.fld_user.setPlaceholderText(_translate("MainWindow", "username"))
        self.lbl_password.setText(_translate("MainWindow", "Password"))
        self.fld_password.setPlaceholderText(_translate("MainWindow", "password"))
        self.btn_test.setText(_translate("MainWindow", "Test Connection"))
        self.lbl_host.setText(_translate("MainWindow", "Host"))
        self.fld_host.setText(_translate("MainWindow", "localhost"))
        self.fld_host.setPlaceholderText(_translate("MainWindow", "host"))
        self.lbl_port.setText(_translate("MainWindow", "Port"))
        self.fld_port.setText(_translate("MainWindow", "5432"))
        self.fld_port.setPlaceholderText(_translate("MainWindow", "port"))
        self.lbl_dbname.setText(_translate("MainWindow", "Database"))
        self.fld_dbname.setPlaceholderText(_translate("MainWindow", "database"))
        self.btn_import.setText(_translate("MainWindow", "Import"))
        self.btn_save_log.setText(_translate("MainWindow", "Save Log"))
        self.menu_File.setTitle(_translate("MainWindow", "&File"))
        self.menu_Help.setTitle(_translate("MainWindow", "&Help"))
        self.act_add.setText(_translate("MainWindow", "&Add File"))
        self.act_about.setText(_translate("MainWindow", "About"))

