# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(600, 700)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.txt_log = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.txt_log.setReadOnly(True)
        self.txt_log.setObjectName("txt_log")
        self.gridLayout.addWidget(self.txt_log, 3, 0, 1, 2)
        self.lbl_log = QtWidgets.QLabel(self.centralwidget)
        self.lbl_log.setObjectName("lbl_log")
        self.gridLayout.addWidget(self.lbl_log, 2, 0, 1, 1)
        self.btn_save_log = QtWidgets.QPushButton(self.centralwidget)
        self.btn_save_log.setObjectName("btn_save_log")
        self.gridLayout.addWidget(self.btn_save_log, 5, 0, 1, 1)
        self.widget_tl = QtWidgets.QWidget(self.centralwidget)
        self.widget_tl.setObjectName("widget_tl")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.widget_tl)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.lbl_host = QtWidgets.QLabel(self.widget_tl)
        self.lbl_host.setObjectName("lbl_host")
        self.gridLayout_3.addWidget(self.lbl_host, 0, 0, 1, 1)
        self.fld_host = QtWidgets.QLineEdit(self.widget_tl)
        self.fld_host.setObjectName("fld_host")
        self.gridLayout_3.addWidget(self.fld_host, 0, 1, 1, 1)
        self.lbl_port = QtWidgets.QLabel(self.widget_tl)
        self.lbl_port.setObjectName("lbl_port")
        self.gridLayout_3.addWidget(self.lbl_port, 1, 0, 1, 1)
        self.fld_port = QtWidgets.QLineEdit(self.widget_tl)
        self.fld_port.setObjectName("fld_port")
        self.gridLayout_3.addWidget(self.fld_port, 1, 1, 1, 1)
        self.lbl_dbname = QtWidgets.QLabel(self.widget_tl)
        self.lbl_dbname.setObjectName("lbl_dbname")
        self.gridLayout_3.addWidget(self.lbl_dbname, 2, 0, 1, 1)
        self.fld_dbname = QtWidgets.QLineEdit(self.widget_tl)
        self.fld_dbname.setObjectName("fld_dbname")
        self.gridLayout_3.addWidget(self.fld_dbname, 2, 1, 1, 1)
        self.gridLayout.addWidget(self.widget_tl, 0, 0, 1, 1)
        self.widget_tr = QtWidgets.QWidget(self.centralwidget)
        self.widget_tr.setObjectName("widget_tr")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widget_tr)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.lbl_user = QtWidgets.QLabel(self.widget_tr)
        self.lbl_user.setObjectName("lbl_user")
        self.gridLayout_2.addWidget(self.lbl_user, 0, 0, 1, 1)
        self.fld_user = QtWidgets.QLineEdit(self.widget_tr)
        self.fld_user.setObjectName("fld_user")
        self.gridLayout_2.addWidget(self.fld_user, 0, 1, 1, 1)
        self.lbl_password = QtWidgets.QLabel(self.widget_tr)
        self.lbl_password.setObjectName("lbl_password")
        self.gridLayout_2.addWidget(self.lbl_password, 1, 0, 1, 1)
        self.fld_password = QtWidgets.QLineEdit(self.widget_tr)
        self.fld_password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.fld_password.setObjectName("fld_password")
        self.gridLayout_2.addWidget(self.fld_password, 1, 1, 1, 1)
        self.btn_test = QtWidgets.QPushButton(self.widget_tr)
        self.btn_test.setObjectName("btn_test")
        self.gridLayout_2.addWidget(self.btn_test, 2, 0, 1, 2)
        self.gridLayout.addWidget(self.widget_tr, 0, 1, 1, 1)
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.btn_clear = QtWidgets.QPushButton(self.tab)
        self.btn_clear.setObjectName("btn_clear")
        self.gridLayout_4.addWidget(self.btn_clear, 1, 2, 1, 1)
        self.btn_remove = QtWidgets.QPushButton(self.tab)
        self.btn_remove.setObjectName("btn_remove")
        self.gridLayout_4.addWidget(self.btn_remove, 1, 1, 1, 1)
        self.btn_add = QtWidgets.QPushButton(self.tab)
        self.btn_add.setObjectName("btn_add")
        self.gridLayout_4.addWidget(self.btn_add, 1, 0, 1, 1)
        self.tbl_file = QtWidgets.QTableWidget(self.tab)
        self.tbl_file.setObjectName("tbl_file")
        self.tbl_file.setColumnCount(5)
        self.tbl_file.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_file.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_file.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_file.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_file.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_file.setHorizontalHeaderItem(4, item)
        self.gridLayout_4.addWidget(self.tbl_file, 0, 0, 1, 3)
        self.btn_import = QtWidgets.QPushButton(self.tab)
        self.btn_import.setObjectName("btn_import")
        self.gridLayout_4.addWidget(self.btn_import, 2, 0, 1, 3)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.btn_fetch = QtWidgets.QPushButton(self.tab_2)
        self.btn_fetch.setObjectName("btn_fetch")
        self.gridLayout_5.addWidget(self.btn_fetch, 1, 0, 1, 1)
        self.btn_clear2 = QtWidgets.QPushButton(self.tab_2)
        self.btn_clear2.setObjectName("btn_clear2")
        self.gridLayout_5.addWidget(self.btn_clear2, 1, 2, 1, 1)
        self.tbl_table = QtWidgets.QTableWidget(self.tab_2)
        self.tbl_table.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tbl_table.setObjectName("tbl_table")
        self.tbl_table.setColumnCount(4)
        self.tbl_table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_table.setHorizontalHeaderItem(3, item)
        self.gridLayout_5.addWidget(self.tbl_table, 0, 0, 1, 3)
        self.btn_remove2 = QtWidgets.QPushButton(self.tab_2)
        self.btn_remove2.setObjectName("btn_remove2")
        self.gridLayout_5.addWidget(self.btn_remove2, 1, 1, 1, 1)
        self.btn_export = QtWidgets.QPushButton(self.tab_2)
        self.btn_export.setObjectName("btn_export")
        self.gridLayout_5.addWidget(self.btn_export, 2, 0, 1, 3)
        self.tabWidget.addTab(self.tab_2, "")
        self.gridLayout.addWidget(self.tabWidget, 1, 0, 1, 2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 600, 22))
        self.menubar.setObjectName("menubar")
        self.menu_File = QtWidgets.QMenu(self.menubar)
        self.menu_File.setObjectName("menu_File")
        self.menu_Help = QtWidgets.QMenu(self.menubar)
        self.menu_Help.setObjectName("menu_Help")
        MainWindow.setMenuBar(self.menubar)
        self.act_add = QtWidgets.QAction(MainWindow)
        self.act_add.setObjectName("act_add")
        self.act_about = QtWidgets.QAction(MainWindow)
        self.act_about.setObjectName("act_about")
        self.menu_File.addAction(self.act_add)
        self.menu_Help.addAction(self.act_about)
        self.menubar.addAction(self.menu_File.menuAction())
        self.menubar.addAction(self.menu_Help.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.fld_host, self.fld_port)
        MainWindow.setTabOrder(self.fld_port, self.fld_dbname)
        MainWindow.setTabOrder(self.fld_dbname, self.fld_user)
        MainWindow.setTabOrder(self.fld_user, self.fld_password)
        MainWindow.setTabOrder(self.fld_password, self.btn_test)
        MainWindow.setTabOrder(self.btn_test, self.tabWidget)
        MainWindow.setTabOrder(self.tabWidget, self.txt_log)
        MainWindow.setTabOrder(self.txt_log, self.btn_save_log)
        MainWindow.setTabOrder(self.btn_save_log, self.tbl_file)
        MainWindow.setTabOrder(self.tbl_file, self.btn_add)
        MainWindow.setTabOrder(self.btn_add, self.btn_remove)
        MainWindow.setTabOrder(self.btn_remove, self.btn_clear)
        MainWindow.setTabOrder(self.btn_clear, self.btn_import)
        MainWindow.setTabOrder(self.btn_import, self.tbl_table)
        MainWindow.setTabOrder(self.tbl_table, self.btn_fetch)
        MainWindow.setTabOrder(self.btn_fetch, self.btn_remove2)
        MainWindow.setTabOrder(self.btn_remove2, self.btn_clear2)
        MainWindow.setTabOrder(self.btn_clear2, self.btn_export)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Shp2PgsqlGUI"))
        self.lbl_log.setText(_translate("MainWindow", "Log"))
        self.btn_save_log.setText(_translate("MainWindow", "Save Log"))
        self.lbl_host.setText(_translate("MainWindow", "Host"))
        self.fld_host.setText(_translate("MainWindow", "localhost"))
        self.fld_host.setPlaceholderText(_translate("MainWindow", "host"))
        self.lbl_port.setText(_translate("MainWindow", "Port"))
        self.fld_port.setText(_translate("MainWindow", "5432"))
        self.fld_port.setPlaceholderText(_translate("MainWindow", "port"))
        self.lbl_dbname.setText(_translate("MainWindow", "Database"))
        self.fld_dbname.setPlaceholderText(_translate("MainWindow", "database"))
        self.lbl_user.setText(_translate("MainWindow", "Username"))
        self.fld_user.setPlaceholderText(_translate("MainWindow", "username"))
        self.lbl_password.setText(_translate("MainWindow", "Password"))
        self.fld_password.setPlaceholderText(_translate("MainWindow", "password"))
        self.btn_test.setText(_translate("MainWindow", "Test Connection"))
        self.btn_clear.setText(_translate("MainWindow", "Clear"))
        self.btn_remove.setText(_translate("MainWindow", "Remove"))
        self.btn_add.setText(_translate("MainWindow", "Add File"))
        item = self.tbl_file.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Shapefile"))
        item = self.tbl_file.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Schema"))
        item = self.tbl_file.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Table"))
        item = self.tbl_file.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Geo Column"))
        item = self.tbl_file.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "SRID"))
        self.btn_import.setText(_translate("MainWindow", "Import"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Import"))
        self.btn_fetch.setText(_translate("MainWindow", "Fetch"))
        self.btn_clear2.setText(_translate("MainWindow", "Clear"))
        item = self.tbl_table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Schema"))
        item = self.tbl_table.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Table"))
        item = self.tbl_table.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Geo Column"))
        item = self.tbl_table.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Destination"))
        self.btn_remove2.setText(_translate("MainWindow", "Remove"))
        self.btn_export.setText(_translate("MainWindow", "Export"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Export"))
        self.menu_File.setTitle(_translate("MainWindow", "&File"))
        self.menu_Help.setTitle(_translate("MainWindow", "&Help"))
        self.act_add.setText(_translate("MainWindow", "&Add File"))
        self.act_about.setText(_translate("MainWindow", "About"))

